stages:
  - test
  - build
  - security
  - package
  - visualize
  - deploy
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  SECURE_LOG_LEVEL: debug
  SAST_JAVA_VERSION: 17
cache:
  paths:
    - ".m2/repository"

keycloak-login-theme:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:latest
  stage: build
  script:
    - apt-get update
    - apt-get install curl unzip openjdk-17-jdk maven -y
    - npm i
    - npm run build-keycloak-theme
  artifacts:
    paths:
      - ./build_keycloak/src/main/resources/theme/
      - ./build_keycloak/target/keycloak-mui-theme-*.jar
docker-build-release:
  stage: package
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.0
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:19.03.0-dind
  needs: [ "keycloak-login-theme" ]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - tags
  except:
    - branches

docker-build-branches:
  stage: package
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.0
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:19.03.0-dind
  needs: [ "keycloak-login-theme" ]
  script:
    - export BRANCH_NAME=$(echo "$CI_COMMIT_REF_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/keycloak:$BRANCH_NAME-latest .
    - docker push $CI_REGISTRY_IMAGE/keycloak:$BRANCH_NAME-latest
  only:
    - branches
  except:
    - tags

docker-build-test:
  stage: package
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.0
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:19.03.0-dind
  needs: [ "keycloak-login-theme" ]
  script:
    - docker build -t $CI_REGISTRY_IMAGE/keycloak:test-build .


